### PR TITLE
Support for ANSI escape sequences in console widget

### PR DESCRIPTION
**Pull request by magro11**
The console widget of itom can now handle ANSI escape sequences (see [https://en.wikipedia.org/wiki/ANSI_escape_code](https://en.wikipedia.org/wiki/ANSI_escape_code)), that can be used to format the output or error texts (e.g. text color, background color, bold, underline, italic...). This feature can also be disabled by a setting in the **Console >> General** tab of the itom property editor.

Python packages, like Sphinx or Numba, are using these codes per default. itom can now identify these codes, and if supported, change the style of the affected parts in the texts.

The **pythonLogWidget**, that can be used in user-defined GUIs for displaying Python output or error streams, can not interpret these ANSI escape sequences (or ANSI escape codes), however there is a new property **removeAnsiEscapeSequences**. If true, the special sequence codes are recognized and removed, but not interpreted. Nevertheless, this allows that the text is not messed up with these strange codes.

For examples, sett the demo **itom/basics/demo_ansiEscapeSequencesOutput.py**:
grafik

### CODE REVIEW

**Review by photoniker — COMMENTED** [review]
I check this feature by building the Sphinx docu. 
Is `[2K` in the beginning of the line interpreated correctly? 

image

**Comment by magro11** [comment]
**ESC[2K**  and other erase sequences will now also be considered and removed. However, they are not interpreted.

**Comment by magro11** [comment]
Still open: If long lines are wrapped, the ANSI escape codes are not interpreted, if they are split at the line limit. --> TODO

**Comment by magro11** [comment]
From my perspective all issues are solved and this PR is ready to merge. @photoniker : what do you think?

**Comment by photoniker** [comment]
I didn't see issues so far...

**Pull request merged**
