### PR TITLE
Alter gtest to 1.12.1

### PR DESCRIPTION
**Pull request by magro11**
In order to remove some CMake and compiler warnings, the **gtest** sources have been altered to version 1.12.1. This is the last version supporting C++11. gtest 1.13 / 1.14 require C++14. This might be ok, too, however the modifications seem to be not really relevant.
Tested with VS2017 / Qt5.12 (single projects) and VS2022 / Qt6.4 (submodule itom-project structure)

### CODE REVIEW

**Comment by photoniker** [comment]
image
Should the cmake variable ``gest_force_shared_crt`` be set to ``ON`` per default?

**Comment by photoniker** [comment]
image
Why are there not tests in unittest_qpropertyeditor?

**Comment by magro11** [comment]
I have no idea if there is a robust way to set **gtest_force_shared_crt** to **ON** per default, probably is should be possible, yes.

**Comment by magro11** [comment]
Update: **gtest_force_shared_crt** is now automatically forced to **ON**.

From my side: ready to merge!

**Review by photoniker — APPROVED** [review]

**Pull request merged**
